# Generated by Django 5.1.15 on 2026-07-04 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frases_historicas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frasehistorica',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
